#微服务注册到eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
server:
  port: 9003
spring:
  application:
    name: ihrm-employee #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm?useUnicode=true&characterEncoding=utf8
    username: root
    password: 111111
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  redis:
    host: 127.0.0.1
    port: 6379

